
<form id="dz_login_forgot_form">
    <h3 class="text-center mb-4 text-black">Contraseña olvidada</h3>
    <div class="form-group">
        <label class="mb-1"  for="val-email-recuperation"><strong>Ingresa tu Email</strong></label>
        <div>
            <input type="email" class="form-control"  id="val-email-recuperation" name="val-email-recuperation" value="Email">
        </div>
    </div>
    <div class="text-center form-group">
        <button type="submit"  class="btn btn-primary btn-block">Enviar</button>
    </div>
</form>